dist: xenial
language: php

php:
  - 7.1
env:
  - LARAVEL_VERSION=5.7.*
matrix:
  fast_finish: true
  # exclude:
  #   - php: 7.0
  #     env: LARAVEL_VERSION=5.6.*
before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - composer install --no-interaction
script:
  - phpunit
